modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/fzzyhmstrs/pc/issues"
license = "MIT"

[[mods]]
modId = "particle_core"
version = "${version}"
displayName = "Particle Core"
authors = "fzzyhmstrs"
description = '''
Particle optimizations. Particle culling, rendering optimization, and configurable disabling of particles.
'''
logoFile = "assets/particle_core/icon.png"

[[mixins]]
config = "particle_core.mixins.json"

[[dependencies.particle_core]]
modId = "neoforge"
type = "REQUIRED"
versionRange = "[21.9.16-beta,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.particle_core]]
modId = "minecraft"
type = "REQUIRED"
versionRange = "[1.21.9,1.21.10]"
ordering = "NONE"
side = "CLIENT"

[[dependencies.particle_core]]
modId = "kotlinforforge"
type = "REQUIRED"
versionRange = "[6.0.0,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.particle_core]]
modId = "fzzy_config"
type = "REQUIRED"
versionRange = "[0.7.5,)"
ordering = "AFTER"
side = "BOTH"